name: yt_cors_proxy
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  http: ^0.13.4
  shelf: ^1.1.0
  shelf_router: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.15.0
